"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Copy, ExternalLink, Layers, Layout, Pencil, Plus, Search, Trash2 } from "lucide-react";
import { api, ApiError } from "@/lib/api";
import { Badge, Button, Dialog, Field, Input, Select, Spinner, Textarea, useConfirm, useToast } from "@/components/ui";
import { slugify } from "@/lib/slugify";

type PageItem = {
  _id: string;
  title: string;
  slug: string;
  description?: string;
  status: "DRAFT" | "PUBLISHED" | "ARCHIVED";
  sections?: Array<any>;
  updatedAt?: string;
};

export default function PagesManagerPage() {
  const router = useRouter();
  const { toast } = useToast();
  const { confirm } = useConfirm();

  const [pages, setPages] = useState<PageItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [q, setQ] = useState("");
  const [statusFilter, setStatusFilter] = useState("");
  const [creating, setCreating] = useState(false);
  const [saving, setSaving] = useState(false);

  // New page modal state
  const [newTitle, setNewTitle] = useState("");
  const [newSlug, setNewSlug] = useState("");
  const [newDescription, setNewDescription] = useState("");
  const [newStatus, setNewStatus] = useState<"DRAFT" | "PUBLISHED">("DRAFT");

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const params = new URLSearchParams({ limit: "50", sort: "order", dir: "asc" });
      if (q) params.set("q", q);
      if (statusFilter) params.set("status", statusFilter);
      const res = await api<{ data: PageItem[] }>(`/api/v1/admin/content/pages?${params.toString()}`);
      setPages(res.data ?? []);
    } catch (err) {
      toast(err instanceof ApiError ? err.message : "Failed to load pages", "error");
    } finally {
      setLoading(false);
    }
  }, [q, statusFilter, toast]);

  useEffect(() => {
    load();
  }, [load]);

  const handleTitleChange = (val: string) => {
    setNewTitle(val);
    if (!newSlug || newSlug === slugify(newTitle)) {
      setNewSlug(slugify(val));
    }
  };

  const createPage = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!newTitle.trim()) {
      toast("Please enter a page title", "error");
      return;
    }
    setSaving(true);
    try {
      const slug = slugify(newSlug || newTitle);
      const res = await api<{ data: PageItem }>("/api/v1/admin/content/pages", {
        method: "POST",
        body: {
          title: newTitle.trim(),
          slug,
          description: newDescription.trim(),
          status: newStatus,
          sections: [
            {
              type: "hero",
              key: `hero-${Date.now()}`,
              label: "Hero Section",
              enabled: true,
              order: 0,
              heading: newTitle.trim(),
              subheading: newDescription.trim() || "Dynamic page generated by KERN CMS.",
              eyebrow: "Page",
              cta: { label: "Explore", href: "#content" },
            },
          ],
        },
      });
      toast("Page created successfully");
      setCreating(false);
      setNewTitle("");
      setNewSlug("");
      setNewDescription("");
      if (res.data?._id) {
        router.push(`/content/pages/${res.data._id}`);
      } else {
        load();
      }
    } catch (err) {
      toast(err instanceof ApiError ? err.message : "Failed to create page", "error");
    } finally {
      setSaving(false);
    }
  };

  const deletePage = async (id: string, title: string) => {
    const ok = await confirm(`Are you sure you want to delete the page "${title}"?`);
    if (!ok) return;

    try {
      await api(`/api/v1/admin/content/pages/${id}`, { method: "DELETE" });
      toast("Page deleted");
      load();
    } catch (err) {
      toast(err instanceof ApiError ? err.message : "Failed to delete page", "error");
    }
  };

  return (
    <div className="flex flex-col gap-6">
      {/* Header */}
      <header className="flex flex-wrap items-end justify-between gap-4">
        <div>
          <h1 className="display text-3xl text-paper">Pages & Builder</h1>
          <p className="mt-1 text-sm text-smoke">
            Create and manage dynamic pages with customizable visual sections.
          </p>
        </div>
        <Button variant="primary" onClick={() => setCreating(true)}>
          <Plus className="h-4 w-4" /> New page
        </Button>
      </header>

      {/* Filters */}
      <div className="flex flex-wrap items-center gap-3">
        <div className="relative flex-1 min-w-[240px]">
          <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-stone" />
          <Input
            value={q}
            onChange={(e) => setQ(e.target.value)}
            placeholder="Search pages by title or slug..."
            className="pl-9"
          />
        </div>
        <Select
          value={statusFilter}
          onChange={(e) => setStatusFilter(e.target.value)}
          className="w-40"
        >
          <option value="">All statuses</option>
          <option value="PUBLISHED">Published</option>
          <option value="DRAFT">Draft</option>
          <option value="ARCHIVED">Archived</option>
        </Select>
      </div>

      {/* Pages List */}
      {loading ? (
        <Spinner label="Loading pages..." />
      ) : pages.length === 0 ? (
        <div className="flex flex-col items-center justify-center rounded border border-line bg-ink p-12 text-center">
          <Layout className="h-10 w-10 text-stone" />
          <h3 className="mt-4 text-base font-medium text-paper">No custom pages found</h3>
          <p className="mt-1 max-w-sm text-xs text-smoke">
            Create your first dynamic page with customized Hero, Services, Team, FAQs, and CTA sections.
          </p>
          <Button variant="primary" size="sm" onClick={() => setCreating(true)} className="mt-5">
            <Plus className="h-3.5 w-3.5" /> Create page
          </Button>
        </div>
      ) : (
        <div className="overflow-x-auto rounded border border-line bg-ink">
          <table className="w-full text-left text-xs">
            <thead className="border-b border-line bg-ink-2 text-stone">
              <tr>
                <th className="px-4 py-3 font-medium">Page Title & Slug</th>
                <th className="px-4 py-3 font-medium">Sections</th>
                <th className="px-4 py-3 font-medium">Status</th>
                <th className="px-4 py-3 font-medium text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-line">
              {pages.map((p) => {
                const sectionCount = p.sections?.length ?? 0;
                return (
                  <tr key={p._id} className="hover:bg-ink-3 transition-colors">
                    <td className="px-4 py-3.5">
                      <div className="flex flex-col gap-0.5">
                        <Link
                          href={`/content/pages/${p._id}`}
                          className="font-medium text-paper hover:text-acid transition-colors"
                        >
                          {p.title}
                        </Link>
                        <span className="font-mono text-[11px] text-stone">/{p.slug}</span>
                      </div>
                    </td>
                    <td className="px-4 py-3.5">
                      <div className="flex items-center gap-1.5 text-smoke">
                        <Layers className="h-3.5 w-3.5 text-acid" />
                        <span>{sectionCount} {sectionCount === 1 ? "section" : "sections"}</span>
                      </div>
                    </td>
                    <td className="px-4 py-3.5">
                      <Badge value={p.status} />
                    </td>
                    <td className="px-4 py-3.5 text-right">
                      <div className="flex items-center justify-end gap-2">
                        <Link
                          href={`/content/pages/${p._id}`}
                          className="flex items-center gap-1 rounded border border-line bg-ink-2 px-2.5 py-1 text-[11px] font-medium text-paper hover:border-acid hover:text-acid transition-all"
                        >
                          <Pencil className="h-3 w-3" /> Edit in Builder
                        </Link>
                        <button
                          type="button"
                          onClick={() => deletePage(p._id, p.title)}
                          className="rounded p-1 text-stone hover:text-red-400 transition-colors"
                          aria-label="Delete page"
                        >
                          <Trash2 className="h-4 w-4" />
                        </button>
                      </div>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}

      {/* Create Page Modal */}
      <Dialog
        open={creating}
        onClose={() => setCreating(false)}
        title="Create New Dynamic Page"
      >
        <form onSubmit={createPage} className="flex flex-col gap-4">
          <Field label="Page Title">
            <Input
              value={newTitle}
              onChange={(e) => handleTitleChange(e.target.value)}
              placeholder="e.g. Manifesto, Careers, Our Story"
              autoFocus
              required
            />
          </Field>
          <Field label="URL Slug" hint="The public URL path for this page (e.g. /manifesto)">
            <Input
              value={newSlug}
              onChange={(e) => setNewSlug(slugify(e.target.value))}
              placeholder="manifesto"
              required
            />
          </Field>
          <Field label="Short Description" hint="Internal summary and default meta description">
            <Textarea
              value={newDescription}
              onChange={(e) => setNewDescription(e.target.value)}
              placeholder="A brief overview of this page..."
              rows={3}
            />
          </Field>
          <Field label="Initial Status">
            <Select
              value={newStatus}
              onChange={(e) => setNewStatus(e.target.value as any)}
            >
              <option value="DRAFT">Draft (Hidden from public site)</option>
              <option value="PUBLISHED">Published (Live immediately)</option>
            </Select>
          </Field>
          <div className="mt-4 flex justify-end gap-2">
            <Button variant="outline" type="button" onClick={() => setCreating(false)}>
              Cancel
            </Button>
            <Button variant="primary" type="submit" loading={saving}>
              Create & Open Builder →
            </Button>
          </div>
        </form>
      </Dialog>
    </div>
  );
}
